server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/minipc_db
    username: minipc
    password: minipc_8845hs
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    properties:
      '[hibernate.SQL]': DEBUG


logging:
  level:
    '[org.hibernate.sql]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]' : TRACE
